### ISSUE TITLE
runtime files

### ISSUE THREAD

**Issue by Hotte37** [steand/optolink#9]
Hello, 
i cannot find the runtime files to download as mentionaed in the readme.

Thus i tried to compile them, but there are errors shown for every file, e.g.:
ViessmannKW.java:[16,16] error: package org.slf4j does not exist.

I also use Eclipse luna. 
Compliance level is 1.7

I am new to java. Do i have to install the slf4j manually or is it done by the IDE (according pom.xml)?
Or can someone give me a link to a compiled runtime?

Best regards
Hotte

**Comment by FulvioSpelta** [comment]
Try the release section: [https://github.com/steand/optolink/releases/tag/1.0.0-RC1](https://github.com/steand/optolink/releases/tag/1.0.0-RC1)
Best regards
f

**Comment by Hotte37** [comment]
Oh man, i didn't see it.
Thank you very much. It is now running...

Some info, that might help others:
I had a version mismatch regarding RXTXcomm.
My system had RXTXcomm 2.2pre2 und the optolink-jar-with-dependencies.jar had 2.1.7.
I simply replaced the class files in the jar file with the class files 2.2pre2.
Now there is now warning anymore.
